default_language_version:
  python: python3.7

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-encoding-pragma
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
